#!/usr/bin/env python3

import os
import sys
import nltk

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    # store screen_name
    screen_name = sys.argv[1]

    # get tweets
    tweets = get_user_timeline(screen_name, 50)
    if (tweets == None):
        sys.exit("Error")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # analyze tweets
    tokenizer = nltk.tokenize.TweetTokenizer()
    for tweet in tweets:
        score, positive_words, negative_words = analyzer.analyze(tweet)
        tokens = tokenizer.tokenize(tweet)
        if score > 0.0:
            print(colored("{} ".format(score), "green"), end="")
        elif score < 0.0:
            print(colored("{} ".format(score), "red"), end="")
        else:
            print(colored("{} ".format(score), "yellow"), end="")
        for token in tokens:
            if token in positive_words:
                print(colored("{} ".format(token), "green"), end="")
            elif token in negative_words:
                print(colored("{} ".format(token), "red"), end="")
            else:
                print(colored("{} ".format(token), "yellow"), end="")
        print("")

if __name__ == "__main__":
    main()